"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class client_status_t(object):
    __slots__ = ["timeStamp", "intersectionID", "vehicleID", "entryTime", "exitTime", "crossingTime"]

    def __init__(self):
        self.timeStamp = 0
        self.intersectionID = 0
        self.vehicleID = ""
        self.entryTime = 0.0
        self.exitTime = 0.0
        self.crossingTime = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(client_status_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qq", self.timeStamp, self.intersectionID))
        __vehicleID_encoded = self.vehicleID.encode('utf-8')
        buf.write(struct.pack('>I', len(__vehicleID_encoded)+1))
        buf.write(__vehicleID_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">ddd", self.entryTime, self.exitTime, self.crossingTime))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != client_status_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return client_status_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = client_status_t()
        self.timeStamp, self.intersectionID = struct.unpack(">qq", buf.read(16))
        __vehicleID_len = struct.unpack('>I', buf.read(4))[0]
        self.vehicleID = buf.read(__vehicleID_len)[:-1].decode('utf-8', 'replace')
        self.entryTime, self.exitTime, self.crossingTime = struct.unpack(">ddd", buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if client_status_t in parents: return 0
        tmphash = (0xaeba227a90003bb6) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if client_status_t._packed_fingerprint is None:
            client_status_t._packed_fingerprint = struct.pack(">Q", client_status_t._get_hash_recursive([]))
        return client_status_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

