"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class request_membership_t(object):
    __slots__ = ["timeStamp", "sender", "receiver", "request"]

    def __init__(self):
        self.timeStamp = 0
        self.sender = ""
        self.receiver = ""
        self.request = False

    def encode(self):
        buf = BytesIO()
        buf.write(request_membership_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timeStamp))
        __sender_encoded = self.sender.encode('utf-8')
        buf.write(struct.pack('>I', len(__sender_encoded)+1))
        buf.write(__sender_encoded)
        buf.write(b"\0")
        __receiver_encoded = self.receiver.encode('utf-8')
        buf.write(struct.pack('>I', len(__receiver_encoded)+1))
        buf.write(__receiver_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">b", self.request))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != request_membership_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return request_membership_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = request_membership_t()
        self.timeStamp = struct.unpack(">q", buf.read(8))[0]
        __sender_len = struct.unpack('>I', buf.read(4))[0]
        self.sender = buf.read(__sender_len)[:-1].decode('utf-8', 'replace')
        __receiver_len = struct.unpack('>I', buf.read(4))[0]
        self.receiver = buf.read(__receiver_len)[:-1].decode('utf-8', 'replace')
        self.request = bool(struct.unpack('b', buf.read(1))[0])
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if request_membership_t in parents: return 0
        tmphash = (0x91e710143b557c0a) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if request_membership_t._packed_fingerprint is None:
            request_membership_t._packed_fingerprint = struct.pack(">Q", request_membership_t._get_hash_recursive([]))
        return request_membership_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

