"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class client_status_t(object):
    __slots__ = ["timeStamp", "data"]

    def __init__(self):
        self.timeStamp = 0
        self.data = [ 0.0 for dim0 in range(5) ]

    def encode(self):
        buf = BytesIO()
        buf.write(client_status_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timeStamp))
        buf.write(struct.pack('>5d', *self.data[:5]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != client_status_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return client_status_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = client_status_t()
        self.timeStamp = struct.unpack(">q", buf.read(8))[0]
        self.data = struct.unpack('>5d', buf.read(40))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if client_status_t in parents: return 0
        tmphash = (0x91dcc0ad9b89bde7) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if client_status_t._packed_fingerprint is None:
            client_status_t._packed_fingerprint = struct.pack(">Q", client_status_t._get_hash_recursive([]))
        return client_status_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

